name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install pytest youtube-dl openai openai-whisper 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Set PYTHONPATH
      run: |
        echo "export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE/backend" >> $GITHUB_ENV

    - name: Test with pytest
      env: 
        PYTHONPATH: backend
      run: |
        cd backend/tests
        pytest integration_testing unit_testing
