name: Frontend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.3' 
          
      - name: Install dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Verify formatting
        working-directory: frontend
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        working-directory: frontend
        run: dart analyze

      - name: Run tests
        working-directory: frontend
        run: flutter test
